
import openai
import pandas as pd
import os

# Load LSTM forecast
df = pd.read_csv("tapstorm_lstm_forecast_output.csv")

# Format forecast preview
def build_prompt(df):
    preview = df.tail(12)[['Month', 'yhat']].to_string(index=False)
    prompt = f"""You are acting as a financial analyst AI. The following is a 12-month cashflow forecast for Tapstorm Studios generated by an LSTM neural network.

Please provide strategic commentary on:
- The overall shape and signal of the forecast
- Volatility and reliability of machine-learned trend
- Suggestions for financial planning or buffer strategy
- Any additional insights based on pattern shifts

Forecast:
{preview}
""" 
    return prompt

# GPT Call Function
def get_lstm_commentary(df):
    prompt = build_prompt(df)
    openai.api_key = os.getenv("OPENAI_API_KEY")

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful financial analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.5,
        max_tokens=500
    )

    return response['choices'][0]['message']['content']

# Example usage:
# df = pd.read_csv("tapstorm_lstm_forecast_output.csv")
# commentary = get_lstm_commentary(df)
# print(commentary)
