
import openai
import pandas as pd
import os

df = pd.read_csv("tapstorm_prophet_forecast_output.csv")

def build_prompt(df):
    preview = df.tail(12).to_string(index=False)
    prompt = f"""You are a financial analyst AI. Here's a 12-month forecast for Tapstorm Studios generated by Prophet.
Provide strategic commentary for the CFO:
- Forecast shape and inflection points
- Seasonality or concerning patterns
- Risks to consider and planning suggestions

Forecast:
{preview}
""" 
    return prompt

def get_prophet_commentary(df):
    prompt = build_prompt(df)
    openai.api_key = os.getenv("OPENAI_API_KEY")
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful financial analyst."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.5,
        max_tokens=500
    )
    return response['choices'][0]['message']['content']
